@echo off
start /B python server.py
start /B python nodes/node1.py
start /B python nodes/node2.py
start /B python nodes/node3.py
start /B python nodes/node4.py
start /B python nodes/node5.py
start /B python nodes/node6.py
start /B python nodes/node7.py
start /B python nodes/node8.py
start /B python drawdata/draw1.py
start /B python drawdata/draw2.py
start /B python drawdata/draw3.py
start /B python drawdata/draw4.py
start /B python drawdata/draw5.py
start /B python drawdata/draw6.py
start /B python drawdata/draw7.py
start /B python drawdata/draw8.py
start /B python Sound/main.py
start /B python Gui.py